#!/bin/sh -e

RTRTR_ETC="/etc/rtrtr.conf"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -f ${RTRTR_ETC} ]; then
        rm ${RTRTR_ETC}
    fi
    ;;
esac

#DEBHELPER#

